[Archive]
bInvalidateOlderFiles=1
sResourceDataDirsFinal=

[AI]
bFaceRandomPointsWhileWandering=1

[Camera]
fMouseWheelZoomSpeed=2.0

[ScreenSplatter]
bBloodSplatterEnabled=1

[Combat]
bDisableCombatDialogue=0
bForceNPCsUseAmmo=0
iImpactDecalMaxResults=50

[Controls]
# Delay in seconds before the player grabs a basic object
fQCZKeyDelay=0.3
# Delay in seconds before the player grabs an interactive object
fZKeyDelay=0.15

[Grass]
fMaxGrassDistance=3.6
bAllowCreateGrass=1
bUseTerrainTintOnGrass=1

[Havok]
iMaxNbParticlesColliders=512
iNumCellWorldExtents=1024

[Display]
fSpaceGlowBackgroundScale=0.0
fStarIntensity=3000.0
fStarfieldBackgroundScale=30.0
fStarfieldStarBrightnessScale=7.5
fStarfieldStarCoordScale=10.0
bHalfResClouds=0
bLayeredMaterialAllSamplersForceUseAnisotropic=1
bAllowFocusShadowsForPlayerSpaceStation=1
bActorSelfShadowing=1
bAllowShadowcasterNPCLights=1
bUseFocusShadowsForNonPlayerShipsInSpace=1
bVolumetricLightingEnable=1
bVolumetricLightingEnableDistantScattering=1
bVolumetricLightingEnableNearSpatialFiltering=0
bVolumetricLightingEnableScatteringVolume=1
bVolumetricLightingFogMapUseWeatherSettings=0
bVolumetricLightingUseAreaLights=0
bVolumetricLightingUseDistanceCulling=1
bVolumetricLightingUseOcclusionCulling=1
bVolumetricLightingUseWeatherSettings=1
bVolumetricLigthingInLiteBrite=0
bVolumetricLigthingUseLightGobos=0
bEnableVolumetricLightingOnParticles=0
bCloudShadowsVolumetricEnabled=1
bAllowReflectionProbeDynamicLights=1
uMaxReflectionProbeShadowsRendered=8
fBloomUpsampleBlendFactor=0.44
fBloomGaussianKernelMinScale=0.11
fBloomGaussianKernelPower=0.66
fSkyOcclusionFallbackNormalShift=-0.4
bSkyOcclusionUseSH=1
fMotionBlurFactor=0.15
bEnableCloudShadows=1
bEnableTerrainShadowsInReflections=1
fDecalLOD0=1000
fDecalLifetime=300
bHalfResolutionCorrection=0
uCSMSplit1Frequency=1
fNearShadowLightRange=36.0
fReflectionProbesMaxDistanceForScore=18000
fShadowReflectionProbeDirectional=0.02
bAllowDiffuseProbeDynamicLights=1
fClusteredLightingFarZ=2048
fClusteredLightingNearZ=1
uCullDistantLightDistanceSquare=1440000
bDiffuseProbeVolumeBlendWeight=1
fDefaultFOV=100
fDefault1stPersonFOV=100
fDefaultWorldFOV=100
fPlanetaryRingBacklightingScale=0.8
iParallelCascadePyramidMipBias=0
uDepthMvFixupMipBias=1
fWaterLightingScale=0.8
fExtendedContactShadowsBaseRayLength=0.12
fExtendedContactShadowsThicknessScale=9
fExtendedContactShadowsRayBias=0.03
fTerrainNormalAmpMult=3.0

[Imagespace]
fSharpenAmount=0
fFilmGrainAmountMax=0
fFilmGrainAmountMin=0
fLensFlareFalloffRange=296

[SAO]
fDistantAOFarDistanceMeters=900.0
fDistantAOMidDistanceMeters=150.0
fDistantAOMidBlendDistanceMeters=100.0
fDistantAOFarBlendDistanceMeters=750.0
fSAOMovementScale=88
fGTAOStepNoiseScale=0.1
fGTAOSliceBlueNoiseScale=0.1
fGTAODenoiseDiagWeight=0.22
fGTAODenoiseLeakStrength=0.25
fGTAODenoiseLeaksThreshold=1.5
fGTAODenoiseBaseBlurAmount=0.2
bSAOTemporalFiltering=1

[StarMap]
bStarMapEnableLifeIcon=1
fStarMapGalaxyFromSystemFadeTime=0.001
fStarMapGalaxyFromSystemZoomTime=0.0001
fStarMapGalaxyToSystemPanTime=0.001
fStarMapGalaxyToSystemZoomFadeTime=0.0001
fStarMapInspectTransitionTime=0.001
fStarMapOrbitsFadeInTime=0.001
fStarMapOrbitsFadeOutTime=0.001
fStarMapSystemTransitionTime=0.001
fResourceVeinOpenDuration=0.001
fResourceVeinCloseDuration=0.001
fResourceVeinHoverDelay=0.03
fStarMapGravityWavesLineThickness=0
bStarMapGalaxyUseFOVZoom=1
fStarMapGalaxyFOVZoomMax=110
fStarMapGalaxyRotationMaxPitch=60
fStarMapGalaxyRotationMaxYaw=90

[Shadows]
bDrawDistantRocksShadows=1
bDrawDistantTreesShadows=1
uCascadesGrassDistance=3
uCascadesRocksDistance=3
uShadowMaskTileResolution=64
uShadowKernelResolution=1024
fSpotShadowLOD0Distance=56.0
fSpotShadowLOD1Distance=80.0
fSpotShadowLOD2Distance=104.0
fMaxShadowDistance=10000
bDirectionalShadowmapsUseLODFade=1
uReflectionProbesShadowMapResolution=256
fDirectionalLightShadowsQuantizeSteps=4096
fFocusShadowMaxExtraNpcDistance=300
uStaticLightShadowThreshold=128
bCullNonPreskinnedDynamicShadows=0
fDynamicLightShadowDistanceCull=160
fDirectionShadowFocusNormalBias=8
fDirectionalShadowFocusBias=2.4
uParallelShadowDataUpdateThreshold=150

[ContactShadows]
bBlurGaussian=1
fMaxDistance=16.0
fMinLightRadius=1
fProximityLimit=0.24
fBaseRayLength=0.28
fRayBias=0.001
fBackfaceShadowIntensity=2.4
fBlurDepthCutoff=0.001
fThicknessScale=6
fThickness=0.018
fTerrainNormalRayBias=0.009
fContactShadowsOffsetNoiseScale=0.0625
fBorderPercent=0.1
fBorderFadePercent=0.2
fScreenSpaceShadowsBackfaceShadowIntensity=1.6
fScreenSpaceShadowsNearThicknessDistance=64
fScreenSpaceShadowsNearThicknessScale=0.016
fScreenSpaceShadowsFarThicknessScale=0.022
fScreenSpaceShadowsFarThicknessDistance=200
fScreenSpaceShadowsThicknessScale=0.006
fScreenSpaceShadowsTerrainBiasSharpness=15
fScreenSpaceShadowsShadowContrast=5

[Terrain]
uMaxTesselationLevel=16
fTerrainLODErrorThreshold=0.1
uMinTesselationLevel=4

[Decals]
fDebrisDecalTimer=10.0

[Weather]
uMaxNumShadowCastingCelestialBodies=99
bEnableDepthBasedFog=1
uMaxNumCelestialBodiesInReflectionProbes=6
bUseSecondarySun=1
fWindHighestFrequency=8.0
fWindSpeedHighestHighMultiplier=2.0
fWindSpeedLowestLowMultiplier=0.01
fSunAngleMinStarVisibility=40

[Particles]
iMaxEmittersStartedPerFrame=100
fAutoRespawnDelay=0.3
iWaterSplashMaxRequestPerFrame=180

[Water]
bReflectSky=1
bForceHighDetailReflections=1
bUseWaterHiRes=1
bReflectExplosions=1
bUseWaterReflectionBlur=1
fRainScale=60.0
bAutoWaterSilhouetteReflections=1
bUseCubeMapReflections=0
fRainDistance=800.0
uRainBaseIntensity=6
bWaterEnableParallax=1
fWetnessPorosity=0.85
iWaterBlurAmount=-1
fNormalsDampeningExponent=0.8
fRippleMaxNormalsDistance=1.0

[ProcGen]
fObjectMapMinPct=0
fProcGenFootprintDitheringScale=0.115
uProcGenMaximumCellRequestsPerIteration=300

[SpaceScattering]
fScatteringScale=0.65
fNearScatteringScale=0.85
fFarScatteringScale=0.45
fDistanceScalar=2.0
fTransmittanceReconstructionDepth=150

[LOD]
fLODDegradeDistance0=50.0
fLODDegradeDistance1=100.0
fLODDegradeDistance2=200.0
fLODDegradeDistance3=400.0
fLODFactorLogBase=25
fScreenSpaceSizeMultiplier=1.66
fMeshLODOverrideDistance=90
fSpecularLODFadeMax=0.5

[WorkshopLOD]
bEnabledWorkshopLOD=0

[Textures]
fTextureLODScreenSizeUpgradeTargetPercent=0.35

[General]
sLocalSavePath=__MO_Saves\
bUseMyGamesDirectory=1
bAlwaysActive=1
bEnableMessageOfTheDay=0
fEncumberedReminderTimer=300
sIntroSequence=0
uMainMenuDelayBeforeAllowSkip=0
bBackgroundLoadVMData=1
bBorderRegionsEnabled=0
bDisableAllGore=0
bPlayMainMenuMusic=1
fMaxLightRadius=90000.0
fFlickeringLightDistance=29.26
fVegetationCollisionActorBaseInfluence=3.0
fVegetationCollisionPAMultiplier=1.0
fVegetationCollisionRunningAttenuation=0.4
fLoadGameFadeSecs=0.1
fNormalFadeSecs=0.1
fAutoDoorFadeSecs=0.1
fNormalDoorFadeSecs=0.1
fMaxActorVegetationCollisionDistance=42

[Boostpack]
bUsePressAndHoldControls=1

[Spaceship]
fShipBuilderMouseZoomSpeedMultiplier=4
fShipBuilderGamepadZoomSpeedMultiplier=1.2
fShipBuilderZoomMinScale=4
fShipBuilderMaxFloor=50
fShipBuilderMinFloor=-50
fShipBuilderMousePanSpeed=2.25
fShipBuilderGamepadPanSpeed=45
fShipBuilderMouseRotationSpeedMultiplier=9
fShipBuilderFloorChangeDuration=0.35
fShipBuilderEquipmentSnapDistance=1.5
fShipBuilderSnapDistance=1.75

[Papyrus]
bEnableLogging=0
bEnableTrace=1
bLoadDebugInformation=1
bEnableProfiling=0
